on: 
  push:
    paths:
      - .github/workflows/download_and_save_to_git.yaml
jobs:
  job1:
    runs-on:ubuntu-latest
    container: rocker/tidyverse
    env:
      GITHUB_PAT: ${{ secrets.pat_github }}
    steps:
      - uses: actions/checkout@v1
      - name: Scrape projects
        run: |
          Rscript hydroquebecoutage.R
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git status  
          git add .   || echo "ECHO No changes to commit"
          git commit -m "automatic update"    || echo "ECHO No changes to commit"
          git push origin || echo "ECHO No changes to commit"
          git status  
     - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          pkgs
          #sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}            