on: 
  push:
    paths:
      - .github/workflows/download_and_save_to_git.yaml
jobs:
  job1:
    runs-on: ubuntu-latest
    container: 
      image: rocker/tidyverse
    env:
      GITHUB_PAT: ${{ secrets.pat_github }}
    steps:
      - uses: actions/checkout@v2
      - name: list files 
        run:  |
          ls * -lh
      - name: list files  data
        run:  |
          ls data/*               
      - name: Scrape projects
        run: |
          Rscript hydroquebecoutage.R
      - name: list files  data
        run:  |
          ls data/*    
      - name: git status
        run:  |
          git status
          pwd
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git status  
          git add .   || echo "ECHO No changes to commit"
          git commit -m "automatic update"    || echo "ECHO No changes to commit"
          git push origin || echo "ECHO No changes to commit"
          git status  
